/**
 * [INPUT]: Reads UpdateService.stagedAppIfReady() + Bundle.main.bundleURL
 * [OUTPUT]: Exports UpdateApplier.applyIfStaged() — call from applicationWillTerminate
 * [POS]: Step 3 of auto-update — swaps the staged bundle onto the running bundle
 *        path via a detached shell script, then relaunches the new binary.
 *
 * Flow:
 *   1. On quit, write apply.sh to the updates directory.
 *   2. Script waits for this PID to exit, rm -rf the current bundle, mv
 *      staged.app into its place, ad-hoc re-signs, then `open` relaunches.
 *   3. Script is spawned detached (setsid + nohup + &) so it outlives us.
 *   4. We return control to NSApp; the actual swap happens after exit.
 *
 * Safety:
 *   - Only runs when UpdateService.stagedAppIfReady() returns a URL — no
 *     staged bundle means zero side effects.
 *   - The script is idempotent: if the mv target and source are identical
 *     (developer sanity), it aborts.
 *   - Ad-hoc re-sign mirrors build_app.sh so Gatekeeper sees a valid signature.
 */

import Foundation
import AppKit

@MainActor
public enum UpdateApplier {

    /// Call from `applicationWillTerminate`. No-op unless a staged bundle is ready.
    public static func applyIfStaged() {
        guard let staged = UpdateService.shared.stagedAppIfReady() else { return }

        let currentBundle = Bundle.main.bundleURL
        let currentPID = ProcessInfo.processInfo.processIdentifier

        // Abort if paths collide (shouldn't happen, defensive)
        guard currentBundle.path != staged.path else { return }

        let updatesDir = staged.deletingLastPathComponent()
        let scriptURL = updatesDir.appendingPathComponent("apply.sh")
        let logURL = updatesDir.appendingPathComponent("apply.log")
        let markerURL = updatesDir.appendingPathComponent("staged.version")

        let script = Self.scriptBody(
            pid: currentPID,
            stagedPath: staged.path,
            destPath: currentBundle.path,
            markerPath: markerURL.path,
            logPath: logURL.path
        )

        do {
            try script.write(to: scriptURL, atomically: true, encoding: .utf8)
            try FileManager.default.setAttributes(
                [.posixPermissions: 0o755], ofItemAtPath: scriptURL.path
            )
        } catch {
            return
        }

        // Spawn detached: setsid ensures the shell survives our exit.
        let task = Process()
        task.launchPath = "/usr/bin/nohup"
        task.arguments = ["/bin/bash", scriptURL.path]
        task.standardOutput = FileHandle.nullDevice
        task.standardError = FileHandle.nullDevice
        task.standardInput = FileHandle.nullDevice
        try? task.run()
    }

    // ──────────────────────────────────────────────
    // MARK: - Script body (visible for tests)
    // ──────────────────────────────────────────────

    /// Generates the bash script. Pure function — no I/O, easy to test.
    public nonisolated static func scriptBody(
        pid: Int32,
        stagedPath: String,
        destPath: String,
        markerPath: String,
        logPath: String
    ) -> String {
        let q = Self.shellQuote
        return """
        #!/bin/bash
        # nanoPod auto-update applier — generated by UpdateApplier.
        # Waits for parent PID to exit, swaps bundle, re-signs, relaunches.
        set -u
        exec > \(q(logPath)) 2>&1
        echo "[$(date)] applier start pid=\(pid)"

        # ──────────────────────────────────────────────
        # 1) Wait for the old app to fully exit
        # ──────────────────────────────────────────────
        for i in $(seq 1 50); do
            if ! kill -0 \(pid) 2>/dev/null; then
                break
            fi
            sleep 0.1
        done
        sleep 0.5

        STAGED=\(q(stagedPath))
        DEST=\(q(destPath))
        MARKER=\(q(markerPath))

        if [ ! -d "$STAGED" ]; then
            echo "staged bundle missing, abort"
            exit 1
        fi

        # ──────────────────────────────────────────────
        # 2) Replace the bundle atomically-ish
        # ──────────────────────────────────────────────
        BACKUP="${DEST}.old-$$"
        if [ -d "$DEST" ]; then
            mv "$DEST" "$BACKUP" || exit 2
        fi

        if ! mv "$STAGED" "$DEST"; then
            echo "mv failed — rolling back"
            [ -d "$BACKUP" ] && mv "$BACKUP" "$DEST"
            exit 3
        fi

        # ──────────────────────────────────────────────
        # 3) Ad-hoc re-sign (mirrors build_app.sh)
        # ──────────────────────────────────────────────
        /usr/bin/codesign --force --deep --sign - "$DEST" || echo "codesign warning (continuing)"

        # ──────────────────────────────────────────────
        # 4) Clean up marker + backup
        # ──────────────────────────────────────────────
        rm -f "$MARKER"
        rm -rf "$BACKUP"

        # ──────────────────────────────────────────────
        # 5) Relaunch the new binary
        # ──────────────────────────────────────────────
        /usr/bin/open "$DEST"
        echo "[$(date)] applier done"
        """
    }

    /// Minimal shell quoting — wraps in single quotes, escapes any inner quotes.
    private nonisolated static func shellQuote(_ s: String) -> String {
        let escaped = s.replacingOccurrences(of: "'", with: "'\\''")
        return "'\(escaped)'"
    }
}
