import XCTest

final class NativeLyricsSurfaceSourceTests: XCTestCase {
    func testNativeSurfaceReservesOverlayInteractionZones() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let surfaceURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsLayerRendererView.swift")
        let source = try String(contentsOf: surfaceURL, encoding: .utf8)

        XCTAssertTrue(source.contains("private func isPointInReservedOverlayZone"))
        XCTAssertTrue(source.contains("nativeLyricsBottomControlsReservedHeight"))
        XCTAssertTrue(source.contains("nativeLyricsTopLeadingReservedWidth"))
        XCTAssertTrue(source.contains("nativeLyricsTopTrailingReservedWidth"))
        XCTAssertTrue(source.contains("guard !isPointInReservedOverlayZone(point, configuration: runtimeConfiguration) else"))
    }

    func testNativeLyricsLayoutInsetsMatchV28SwiftUIRenderer() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let surfaceURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsLayerRendererView.swift")
        let lyricsViewURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsView.swift")
        let measurementURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/NativeLyricsRowMeasurement.swift")
        let surfaceSource = try String(contentsOf: surfaceURL, encoding: .utf8)
        let lyricsViewSource = try String(contentsOf: lyricsViewURL, encoding: .utf8)
        let measurementSource = try String(contentsOf: measurementURL, encoding: .utf8)

        XCTAssertTrue(surfaceSource.contains("private let nativeLyricContentLeadingInset: CGFloat = 32"))
        XCTAssertTrue(surfaceSource.contains("private let nativeLyricContentTrailingInset: CGFloat = 32"))
        XCTAssertTrue(lyricsViewSource.contains("private let lyricContentLeadingInset: CGFloat = 32"))
        XCTAssertTrue(lyricsViewSource.contains("private let lyricContentTrailingInset: CGFloat = 32"))
        XCTAssertTrue(measurementSource.contains("static let leadingInset: CGFloat = 32"))
        XCTAssertTrue(measurementSource.contains("static let trailingInset: CGFloat = 32"))
    }

    func testNativeSurfaceReconcilesViewportRowsDuringManualScroll() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let surfaceURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsLayerRendererView.swift")
        let source = try String(contentsOf: surfaceURL, encoding: .utf8)

        XCTAssertFalse(source.contains("if configuration.effectiveIsManualScrolling {\n            return configuration.rows\n        }"))
        XCTAssertTrue(source.contains("let previousViewportIndex = manualViewportIndex(for: runtimeConfiguration)"))
        XCTAssertTrue(source.contains("let updatedViewportIndex = manualViewportIndex(for: updatedRuntimeConfiguration)"))
        XCTAssertTrue(source.contains("if updatedViewportIndex != previousViewportIndex {"))
        XCTAssertTrue(source.contains("manualScrollState.begin(frozenDisplayIndex: configuration.effectiveScrollTargetIndex)"))
        XCTAssertTrue(source.contains("reconcileVisibleRowViews(\n            runtimeConfiguration: runtimeConfiguration,\n            snapPositions: true"))
        XCTAssertTrue(source.contains("manualIndices.formUnion(geometryVisibleRowIndices(for: configuration))"))
    }

    func testNativeSurfaceKeepsGeometryVisibleRowsMounted() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let surfaceURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsLayerRendererView.swift")
        let source = try String(contentsOf: surfaceURL, encoding: .utf8)

        XCTAssertTrue(source.contains("private func geometryVisibleRowIndices("))
        XCTAssertTrue(source.contains("let viewportPadding: CGFloat = 120"))
        XCTAssertTrue(source.contains("let frame = CGRect(x: 0, y: minY, width: configuration.rowWidth, height: height)"))
        XCTAssertTrue(source.contains("return frame.intersects(viewport) ? row.index : nil"))
        XCTAssertTrue(source.contains(")).union(geometryVisibleRowIndices(for: configuration))"))
    }

    func testSplitDisplayLinesDoNotDuplicateFallbackTranslationAcrossSegments() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let lyricsViewURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsView.swift")
        let source = try String(contentsOf: lyricsViewURL, encoding: .utf8)
        guard let functionStart = source.range(of: "private func makeDisplayLyricLines")?.lowerBound,
              let functionEnd = source.range(of: "private func shouldKeepDisplayLineUnsplit")?.lowerBound else {
            XCTFail("Could not locate makeDisplayLyricLines in LyricsView.swift")
            return
        }
        let body = String(source[functionStart..<functionEnd])

        XCTAssertTrue(
            body.contains("translation: translationSegments.indices.contains(segmentIndex)\n                        ? translationSegments[segmentIndex]\n                        : nil"),
            "Split display rows must leave unmatched translation segments empty instead of repeating the full translation on later rows."
        )
    }

    func testNativeSurfaceDoesNotHostSwiftUIRowViews() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let surfaceURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsLayerRendererView.swift")
        let lyricsViewURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsView.swift")
        let metricsURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/NativeLyricsUXMetrics.swift")
        let source = try String(contentsOf: surfaceURL, encoding: .utf8)
        let lyricsViewSource = try String(contentsOf: lyricsViewURL, encoding: .utf8)
        let metricsSource = try String(contentsOf: metricsURL, encoding: .utf8)

        XCTAssertFalse(source.contains("NSHostingView"))
        XCTAssertFalse(source.contains("AnyView"))
        XCTAssertFalse(source.contains("LyricLineView("))
        XCTAssertTrue(source.contains("NativeLyricsRowView"))
        XCTAssertTrue(source.contains("CATextLayer"))
        XCTAssertTrue(source.contains("NativeLyricsFrameCadenceAccumulator"))
        XCTAssertTrue(source.contains("NativeLyricsDisplayLinkScheduler"))
        XCTAssertTrue(source.contains("displayLinkScheduler.enqueue"))
        XCTAssertTrue(source.contains("let delta = lastPresentationTick.map { max(0, now - $0) }"))
        XCTAssertTrue(source.contains("private static func hasTimelineTargetChange("))
        XCTAssertFalse(source.contains("previousTimelineState != nativeTimelineState"))
        XCTAssertTrue(source.contains("manualPresentationNeedsApply"))
        XCTAssertTrue(source.contains("rowViewReusePool"))
        XCTAssertTrue(source.contains("prepareForReuse()"))
        XCTAssertTrue(source.contains("cachedStaticTextPlanKey = nil"))
        XCTAssertTrue(source.contains("mainBrightTextLayer.mask = mainSweepMaskLayer"))
        XCTAssertTrue(source.contains("private let mainBaseRevealMaskLayer = CALayer()"))
        XCTAssertTrue(source.contains("private var mainBaseRevealLineLayers: [NativeLyricsSweepMaskLineLayer] = []"))
        // v2.8 karaoke: the dim base text is NEVER masked — the full line is always visible at
        // dimAlpha and only the bright overlay sweeps. (Masking the base caused the "从无到有"
        // words-materialize-from-nothing bug.)
        XCTAssertFalse(source.contains("mainTextLayer.mask = appliesMainSweep ? mainBaseRevealMaskLayer"))
        XCTAssertTrue(source.contains("the dim base text stays fully visible at dimAlpha at ALL times"))
        XCTAssertTrue(source.contains("hideBaseRevealMaskLayers()"))
        XCTAssertTrue(source.contains("translationBrightTextLayer.mask = translationSweepMaskLayer"))
        XCTAssertTrue(source.contains("hideDotLayers()"))
        XCTAssertTrue(source.contains("NativeLyricsDotPhasePlan.baseDotSize"))
        XCTAssertTrue(source.contains("NativeLyricsDotPhasePlan.baseDotSpacing"))
        // v2.8 dot parity: each dot scales individually; container stays identity.
        XCTAssertTrue(source.contains("let scale = plan.scales.indices.contains(index) ? plan.scales[index] : 1"))
        XCTAssertTrue(source.contains("dotContainerLayer.setAffineTransform(.identity)"))
        XCTAssertTrue(source.contains("dot.setAffineTransform(CGAffineTransform(scaleX: scale"))
        XCTAssertTrue(source.contains("queueNativeManualScrollPresentation()"))
        XCTAssertTrue(source.contains("if shouldApplyManualPresentation"))
        XCTAssertTrue(source.contains("manualViewportIndex(for configuration"))
        XCTAssertFalse(source.contains("applyNativeManualScrollPresentation()"))
        XCTAssertFalse(source.contains("let tickTimestamp = displayTimestamp ?? now"))
        XCTAssertFalse(source.contains("lastPresentationTick = tickTimestamp"))
        XCTAssertTrue(source.contains("lyrics.nativeRenderer.summary"))
        XCTAssertTrue(source.contains("lyrics.nativeRenderer.configure"))
        XCTAssertTrue(source.contains("private func visibleRows(for configuration: LyricsLayerRendererConfiguration)"))
        XCTAssertTrue(source.contains("override func scrollWheel(with event: NSEvent)"))
        XCTAssertTrue(source.contains("NSEvent.addLocalMonitorForEvents(matching: [.scrollWheel, .leftMouseDown, .mouseMoved])"))
        XCTAssertTrue(source.contains("private func handleNativeScrollWheel(_ event: NSEvent) -> Bool"))
        XCTAssertTrue(source.contains("private func handleNativeMouseDown(_ event: NSEvent) -> Bool"))
        XCTAssertTrue(source.contains("shouldHandleLocalEvent(event)"))
        XCTAssertTrue(source.contains("return event.type == .scrollWheel && manualScrollState.isActive"))
        XCTAssertTrue(source.contains("private func deferParentCallback"))
        XCTAssertTrue(source.contains("guard isInsideSurface || manualScrollState.isActive else"))
        XCTAssertTrue(source.contains("override func acceptsFirstMouse(for event: NSEvent?) -> Bool"))
        XCTAssertTrue(source.contains("override func hitTest(_ point: NSPoint) -> NSView? {\n        nil\n    }"))
        XCTAssertTrue(source.contains("NativeLyricsManualScrollState"))
        XCTAssertTrue(source.contains("handleNativeLineTap"))
        XCTAssertTrue(lyricsViewSource.contains("onLineTap: { line in handleLineTap(line: line, requestNativeDirectSnap: false) }"))
        XCTAssertTrue(lyricsViewSource.contains("lyricsLayerRendererActive && requestNativeDirectSnap"))
        XCTAssertTrue(source.contains("mainSweepMaskLayer"))
        XCTAssertTrue(source.contains("mainPerRunSweepMaskLayer"))
        XCTAssertTrue(source.contains("updatePerRunSweepMask"))
        XCTAssertTrue(source.contains("translationSweepMaskLayer"))
        XCTAssertTrue(source.contains("mainTextLayer.setAffineTransform(.identity)"))
        XCTAssertFalse(source.contains("mainTextLayer.setAffineTransform(CGAffineTransform(translationX: 0, y: y))"))
        XCTAssertTrue(source.contains("let appliesMainSweep = isActive && row.displayLine.line.hasSyllableSync && !plan.wordRuns.isEmpty"))
        XCTAssertTrue(source.contains("let appliesTranslationSweep = appliesMainSweep"))
        XCTAssertTrue(source.contains("isAwaitingTranslation(row: row, configuration: configuration)"))
        XCTAssertTrue(source.contains("isTranslationFailureVisible(row: row, configuration: configuration)"))
        XCTAssertFalse(source.contains("configuration.showTranslation && (configuration.isTranslating || configuration.translationFailed)"))
        XCTAssertTrue(source.contains("translationLoadingDotContainerLayer"))
        XCTAssertTrue(source.contains("startTranslationLoadingDots()"))
        XCTAssertTrue(source.contains("NativeLyricsTranslationLoadingDotPhasePlan.dotSize"))
        XCTAssertTrue(source.contains("NativeLyricsTranslationLoadingDotPhasePlan.dotSpacing"))
        XCTAssertTrue(source.contains("NativeLyricsTranslationLoadingDotPhasePlan.dotOpacity"))
        XCTAssertFalse(source.contains("animation.beginTime = CACurrentMediaTime() + Double(index)"))
        XCTAssertFalse(source.contains("attributedText(\"•••\""))
        XCTAssertFalse(source.contains("Translation unavailable"))
        XCTAssertTrue(source.contains("expectsNoLineLevelMainSweep"))
        XCTAssertTrue(source.contains("appliesLineLevelMainSweep"))
        XCTAssertTrue(metricsSource.contains("unexpectedLineLevelMainSweepCount"))
        XCTAssertTrue(metricsSource.contains("unexpectedLineLevelTranslationSweepCount"))
        XCTAssertTrue(metricsSource.contains("baseRevealSampleCount"))
        XCTAssertTrue(metricsSource.contains("baseRevealGapCount"))
        XCTAssertTrue(metricsSource.contains("baseRevealLineCoverageGapCount"))
        XCTAssertTrue(metricsSource.contains("baseRevealWavefrontErrorMax"))
        XCTAssertTrue(metricsSource.contains("static let baseDotSize: CGFloat = NativeLyricsTextConstants().mainFontSize * 0.5"))
        XCTAssertTrue(metricsSource.contains("static let baseDotSpacing: CGFloat = NativeLyricsTextConstants().mainFontSize * 0.25 + 4"))
        // v2.8 InterludeDotsView dot parity (replaced the AMLL all-dots "loading" breathing).
        XCTAssertTrue(metricsSource.contains("let dotsActiveDuration = max(0.1, totalDuration - fadeOutDuration)"))
        XCTAssertTrue(metricsSource.contains("(0.85 + progress * 0.15)"))
        XCTAssertTrue(metricsSource.contains("blur: fadeOutProgress * 8"))
        XCTAssertFalse(metricsSource.contains("let targetBreatheDuration"))
        XCTAssertFalse(metricsSource.contains("globalOpacity"))
        XCTAssertTrue(source.contains("fileprivate func recordTextPhase"))
        XCTAssertFalse(source.contains("|| (configuration.showTranslation && activeRow.displayLine.line.translation?.isEmpty == false)"))
        XCTAssertTrue(source.contains("lyricRenderTime()"))
        XCTAssertTrue(source.contains("runtimeConfiguration.nativeDirectSnapIndex = pending.targetIndex"))
        XCTAssertTrue(source.contains("renderTelemetry.recordTapToLineTiming"))
        XCTAssertTrue(source.contains("pendingTapToLineSettleTiming"))
        XCTAssertTrue(source.contains("private func checkPendingTapToLineSettleTiming"))
        XCTAssertTrue(source.contains("let expectedY = snapY(for: row, configuration: runtimeConfiguration)"))
        XCTAssertTrue(source.contains("abs(appliedY - expectedY) <= 0.5 || now >= pending.deadline"))
        XCTAssertTrue(source.contains("cachedStaticTextPlan"))
        XCTAssertTrue(source.contains("NativeLyricsStaticTextRenderPlan.make"))
        XCTAssertTrue(source.contains("NativeLyricsTextMeasurement.measuredTextHeight"))
        XCTAssertTrue(source.contains("NativeLyricsHeightAccumulator.accumulatedHeights"))
        XCTAssertTrue(source.contains("runtimeConfiguration.accumulatedHeights = NativeLyricsHeightAccumulator.accumulatedHeights"))
        XCTAssertTrue(source.contains("let containmentBounds = geometryBounds.isNull ? bounds : geometryBounds"))
        XCTAssertTrue(source.contains("nativeSemanticCurrentIndex"))
        XCTAssertTrue(source.contains("scheduleNativeLineAdvanceTimerIfNeeded"))
        XCTAssertTrue(source.contains("NativeLyricsTimelinePolicy.amllState"))
        XCTAssertTrue(source.contains("lineInterval: runtimeConfiguration.lineInterval,\n                hasSyllableSync: runtimeConfiguration.hasSyllableSync,\n                isInterludeActive: runtimeConfiguration.interludeAfterIndex != nil"))
        XCTAssertTrue(source.contains("waveTimelineEnabled"))
        XCTAssertTrue(source.contains("rowTapHandlers[hoveredRowIndex]"))
        XCTAssertTrue(source.contains("override func mouseMoved(with event: NSEvent)"))
        XCTAssertTrue(source.contains("updateNativeHoverFromEvent"))
        // D1/D2 fix: tap-to-jump and manual-scroll recovery now spring (v2.8 parity)
        // instead of hard-snapping.
        XCTAssertFalse(source.contains("forceDirectSnap(to: rowIndex, reason: .tapToLine)"))
        XCTAssertFalse(source.contains("forceDirectSnap(to: liveIndex, reason: .manualScroll)"))
        XCTAssertTrue(source.contains("let onLineTap = configuration?.onLineTap"))
        XCTAssertTrue(source.contains("onLineTap?(line)"))
        XCTAssertTrue(source.contains("deferParentCallback {\n            onManualScrollDelta(deltaY, velocity)\n        }"))
        XCTAssertTrue(source.contains("private func reconcileVisibleRowViews("))
        XCTAssertTrue(source.contains("reconcileVisibleRowViews(\n            runtimeConfiguration: runtimeConfiguration,\n            snapPositions: true"))
        XCTAssertTrue(source.contains("semanticSpringRetarget("))
        XCTAssertTrue(source.contains("semanticSpringRetarget(to: liveIndex, reason: .manualScroll"))
        XCTAssertTrue(source.contains("NativeLyricsVisualMotionState"))
        XCTAssertTrue(source.contains("NativeLyricsVisualTarget.amllTarget"))
        XCTAssertTrue(source.contains("staticOpacity: 1"))
        XCTAssertTrue(source.contains("configuration.effectiveIsManualScrolling"))
        XCTAssertTrue(source.contains("if presentationEngine.isNaturalWaveActive"))
        XCTAssertTrue(source.contains("updateNativeLineMotionSamplingTimer"))
        XCTAssertTrue(source.contains("sampleNativeLineMotionIfNeeded"))
        XCTAssertTrue(source.contains("sampleNativeLineMotionDuringPresentationTickIfNeeded"))
        XCTAssertTrue(source.contains("let sampleInterval = min(policyInterval, LyricMotionSamplingPolicy.focusedInterval)"))
        XCTAssertTrue(source.contains("configuration: runtimeConfiguration,\n            timestamp: now"))
        XCTAssertTrue(source.contains("final class NativeLyricsSurfaceController"))
        XCTAssertTrue(source.contains("func captureLineMotionFrames(timestamp: Date, playbackTime: TimeInterval) -> Bool"))
        XCTAssertTrue(lyricsViewSource.contains("@State private var nativeLyricsSurfaceController = NativeLyricsSurfaceController()"))
        XCTAssertTrue(source.contains("private var rowIDByIndex: [Int: String]"))
        XCTAssertTrue(source.contains("private var lastConfiguredTextPhaseIndex: Int?"))
        XCTAssertTrue(source.contains("activeTextPhaseRow(for: runtimeConfiguration)"))
        XCTAssertTrue(source.contains("applyFrames(runtimeConfiguration: runtimeConfiguration, snap: false, managesTransaction: false)"))
        XCTAssertTrue(source.contains("let needsActivationRefresh = textPhaseIndexChanged"))
        XCTAssertTrue(source.contains("row.index == activeTextPhaseIndex"))
        XCTAssertTrue(source.contains("private func refreshTextRowsForActiveLineChange("))
        XCTAssertTrue(source.contains("previousIndex: previousSemanticIndex"))
        XCTAssertTrue(source.contains("if activeTextLineChanged {\n                refreshTextRowsForActiveLineChange"))
        XCTAssertFalse(source.contains("private func textPhaseRows"))
        XCTAssertFalse(source.contains("rowViews.values.compactMap(\\.currentRow).filter"))
        XCTAssertFalse(source.contains("applyFramesForCurrentConfiguration(snap: false, managesTransaction: false)"))
        XCTAssertFalse(lyricsViewSource.contains("@StateObject private var diagnostics"))
        XCTAssertTrue(lyricsViewSource.contains("private let diagnostics = DiagnosticsService.shared"))
        XCTAssertTrue(lyricsViewSource.contains("lineMotionDiagnosticsEnabledSnapshot && currentPage == .lyrics"))
        XCTAssertTrue(lyricsViewSource.contains("handleNativeScrollChromeDelta(deltaY, velocity: velocity)"))
        XCTAssertTrue(lyricsViewSource.contains("handleScrollChromeDelta(deltaY, velocity: velocity)"))
        XCTAssertTrue(lyricsViewSource.contains("nativeLyricsManualScrollActive = true"))
        XCTAssertTrue(lyricsViewSource.contains("lyricsService.isManualScrolling = true"))
        XCTAssertTrue(lyricsViewSource.contains("if isHovering { animateControlsIn() }"))
        XCTAssertFalse(lyricsViewSource.contains("let shouldHideControls = deltaY < 0 || abs(velocity) >= 800"))
        XCTAssertFalse(lyricsViewSource.contains("withTransaction(transaction) {\n            if shouldHideControls"))
        XCTAssertTrue(lyricsViewSource.contains("private var shouldMountBottomControls: Bool {\n        currentPage == .lyrics\n    }"))
        XCTAssertFalse(lyricsViewSource.contains("DispatchQueue.main.asyncAfter(deadline: .now() + unmountDelay)"))
        XCTAssertTrue(lyricsViewSource.contains("if lyricsService.showTranslation,\n           !lyricsService.isTranslating {\n            let visibleTranslationPartials = partials.filter"))
        XCTAssertFalse(lyricsViewSource.contains("onManualScrollDelta: { deltaY, velocity in\n                            handleScrollChromeDelta"))
        XCTAssertFalse(source.contains("fallback: configuration.lineTargetIndices[row.index]"))
        XCTAssertFalse(source.contains("wordFillBucket"))
        XCTAssertFalse(lyricsViewSource.contains("Timer.publish"))
        XCTAssertTrue(lyricsViewSource.contains("lineMotionMonitoringEnabled && !lyricsLayerRendererActive"))
        XCTAssertFalse(lyricsViewSource.contains("nativeLineMotionFrameCaptureSequence"))
        XCTAssertFalse(source.contains("lineMotionFrameCaptureSequence"))
        XCTAssertFalse(lyricsViewSource.contains("scroll.lastVelocity = absVelocity"))
        XCTAssertTrue(lyricsViewSource.contains("recordLyricsRendererModeEvent(reason: \"track\")"))
        XCTAssertFalse(source.contains("if reason != \"interval\" {\n            flushRenderTelemetry"))
    }

    func testLyricsUXBenchmarkRequiresNativeRendererModeEvidence() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let scriptURL = repoRoot.appendingPathComponent("scripts/lyrics_ux_benchmark.py")
        let source = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(source.contains("def collect_renderer_mode("))
        XCTAssertTrue(source.contains("\"lyrics.rendererMode\""))
        XCTAssertTrue(source.contains("lyrics renderer never reported native mode"))
        XCTAssertTrue(source.contains("renderer_mode_steps"))
        XCTAssertTrue(source.contains("summary[\"steps\"][\"rendererMode\"]"))
        XCTAssertTrue(source.contains("unexpectedLineLevelMainSweepCount"))
        XCTAssertTrue(source.contains("no active line-level no-sweep samples"))
        XCTAssertTrue(source.contains("\"baseRevealSampleCount\""))
        XCTAssertTrue(source.contains("no active syllable base reveal samples"))
        XCTAssertTrue(source.contains("base reveal gap count"))
        XCTAssertTrue(source.contains("base reveal wavefront error max"))
        XCTAssertTrue(source.contains("\"cjkEmphasisGlyphCount\""))
        XCTAssertTrue(source.contains("CJK emphasis glyph count"))
        XCTAssertTrue(
            source.contains("parser.add_argument(\"--min-cpu-reduction\", type=float, default=0.70)"),
            "The UX gate must preserve the native renderer's 70%+ CPU reduction target instead of accepting weak CPU parity."
        )
    }
}
