import XCTest

final class NativeLyricsSurfaceSourceTests: XCTestCase {
    func testNativeSurfaceDoesNotHostSwiftUIRowViews() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let surfaceURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsLayerRendererView.swift")
        let lyricsViewURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsView.swift")
        let source = try String(contentsOf: surfaceURL, encoding: .utf8)
        let lyricsViewSource = try String(contentsOf: lyricsViewURL, encoding: .utf8)

        XCTAssertFalse(source.contains("NSHostingView"))
        XCTAssertFalse(source.contains("AnyView"))
        XCTAssertFalse(source.contains("LyricLineView("))
        XCTAssertTrue(source.contains("NativeLyricsRowView"))
        XCTAssertTrue(source.contains("CATextLayer"))
        XCTAssertTrue(source.contains("NativeLyricsFrameCadenceAccumulator"))
        XCTAssertTrue(source.contains("lyrics.nativeRenderer.summary"))
        XCTAssertTrue(source.contains("lyrics.nativeRenderer.configure"))
        XCTAssertTrue(source.contains("private func visibleRows(for configuration: LyricsLayerRendererConfiguration)"))
        XCTAssertTrue(source.contains("override func scrollWheel(with event: NSEvent)"))
        XCTAssertTrue(source.contains("NativeLyricsManualScrollState"))
        XCTAssertTrue(source.contains("handleNativeLineTap"))
        XCTAssertTrue(source.contains("mainSweepMaskLayer"))
        XCTAssertTrue(source.contains("mainPerRunSweepMaskLayer"))
        XCTAssertTrue(source.contains("updatePerRunSweepMask"))
        XCTAssertTrue(source.contains("translationSweepMaskLayer"))
        XCTAssertTrue(source.contains("lyricRenderTime()"))
        XCTAssertTrue(source.contains("runtimeConfiguration.nativeDirectSnapIndex = targetIndex"))
        XCTAssertTrue(source.contains("renderTelemetry.recordTapToLineTiming"))
        XCTAssertTrue(source.contains("cachedStaticTextPlan"))
        XCTAssertTrue(source.contains("NativeLyricsStaticTextRenderPlan.make"))
        XCTAssertTrue(source.contains("nativeSemanticCurrentIndex"))
        XCTAssertTrue(source.contains("scheduleNativeLineAdvanceTimerIfNeeded"))
        XCTAssertTrue(source.contains("NativeLyricsTimelinePolicy.liveDisplayIndex"))
        XCTAssertTrue(source.contains("waveTimelineEnabled"))
        XCTAssertTrue(source.contains("rowTapHandlers[hoveredRowIndex]"))
        XCTAssertTrue(source.contains("if presentationEngine.isNaturalWaveActive"))
        XCTAssertTrue(source.contains("updateNativeLineMotionSamplingTimer"))
        XCTAssertTrue(source.contains("sampleNativeLineMotionIfNeeded"))
        XCTAssertTrue(source.contains("configuration: runtimeConfiguration,\n            timestamp: now"))
        XCTAssertTrue(source.contains("final class NativeLyricsSurfaceController"))
        XCTAssertTrue(source.contains("func captureLineMotionFrames(timestamp: Date, playbackTime: TimeInterval) -> Bool"))
        XCTAssertTrue(lyricsViewSource.contains("@State private var nativeLyricsSurfaceController = NativeLyricsSurfaceController()"))
        XCTAssertTrue(source.contains("private var rowIDByIndex: [Int: String]"))
        XCTAssertTrue(source.contains("private var lastConfiguredTextPhaseIndex: Int?"))
        XCTAssertTrue(source.contains("activeTextPhaseRow(for: runtimeConfiguration)"))
        XCTAssertTrue(source.contains("applyFrames(runtimeConfiguration: runtimeConfiguration, snap: false, managesTransaction: false)"))
        XCTAssertTrue(source.contains("let needsActivationRefresh = textPhaseIndexChanged"))
        XCTAssertTrue(source.contains("row.index == activeTextPhaseIndex"))
        XCTAssertFalse(source.contains("private func textPhaseRows"))
        XCTAssertFalse(source.contains("rowViews.values.compactMap(\\.currentRow).filter"))
        XCTAssertFalse(source.contains("applyFramesForCurrentConfiguration(snap: false, managesTransaction: false)"))
        XCTAssertFalse(lyricsViewSource.contains("@StateObject private var diagnostics"))
        XCTAssertTrue(lyricsViewSource.contains("private let diagnostics = DiagnosticsService.shared"))
        XCTAssertTrue(lyricsViewSource.contains("lineMotionDiagnosticsEnabledSnapshot && currentPage == .lyrics"))
        XCTAssertTrue(lyricsViewSource.contains("handleNativeScrollChromeDelta(deltaY, velocity: velocity)"))
        XCTAssertTrue(lyricsViewSource.contains("transaction.disablesAnimations = true"))
        XCTAssertTrue(lyricsViewSource.contains("if lyricsService.showTranslation,\n           !lyricsService.isTranslating {\n            let visibleTranslationPartials = partials.filter"))
        XCTAssertFalse(lyricsViewSource.contains("onManualScrollDelta: { deltaY, velocity in\n                            handleScrollChromeDelta"))
        XCTAssertFalse(source.contains("fallback: configuration.lineTargetIndices[row.index]"))
        XCTAssertFalse(source.contains("wordFillBucket"))
        XCTAssertFalse(lyricsViewSource.contains("Timer.publish"))
        XCTAssertTrue(lyricsViewSource.contains("lineMotionMonitoringEnabled && !lyricsLayerRendererActive"))
        XCTAssertFalse(lyricsViewSource.contains("nativeLineMotionFrameCaptureSequence"))
        XCTAssertFalse(source.contains("lineMotionFrameCaptureSequence"))
        XCTAssertFalse(lyricsViewSource.contains("scroll.lastVelocity = absVelocity"))
    }
}
