import XCTest

final class NativeLyricsSurfaceSourceTests: XCTestCase {
    func testNativeSurfaceDoesNotHostSwiftUIRowViews() throws {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let surfaceURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsLayerRendererView.swift")
        let lyricsViewURL = repoRoot.appendingPathComponent("Sources/MusicMiniPlayerCore/UI/LyricsView.swift")
        let source = try String(contentsOf: surfaceURL, encoding: .utf8)
        let lyricsViewSource = try String(contentsOf: lyricsViewURL, encoding: .utf8)

        XCTAssertFalse(source.contains("NSHostingView"))
        XCTAssertFalse(source.contains("AnyView"))
        XCTAssertFalse(source.contains("LyricLineView("))
        XCTAssertTrue(source.contains("NativeLyricsRowView"))
        XCTAssertTrue(source.contains("CATextLayer"))
        XCTAssertTrue(source.contains("NativeLyricsFrameCadenceAccumulator"))
        XCTAssertTrue(source.contains("lyrics.nativeRenderer.summary"))
        XCTAssertTrue(source.contains("lyrics.nativeRenderer.configure"))
        XCTAssertTrue(source.contains("private func visibleRows(for configuration: LyricsLayerRendererConfiguration)"))
        XCTAssertTrue(source.contains("override func scrollWheel(with event: NSEvent)"))
        XCTAssertTrue(source.contains("NativeLyricsManualScrollState"))
        XCTAssertTrue(source.contains("handleNativeLineTap"))
        XCTAssertTrue(source.contains("mainSweepMaskLayer"))
        XCTAssertTrue(source.contains("mainPerRunSweepMaskLayer"))
        XCTAssertTrue(source.contains("updatePerRunSweepMask"))
        XCTAssertTrue(source.contains("translationSweepMaskLayer"))
        XCTAssertTrue(source.contains("lyricRenderTime()"))
        XCTAssertTrue(source.contains("runtimeConfiguration.nativeDirectSnapIndex = targetIndex"))
        XCTAssertTrue(source.contains("renderTelemetry.recordTapToLineTiming"))
        XCTAssertTrue(source.contains("cachedStaticTextPlan"))
        XCTAssertTrue(source.contains("NativeLyricsStaticTextRenderPlan.make"))
        XCTAssertTrue(source.contains("nativeSemanticCurrentIndex"))
        XCTAssertTrue(source.contains("scheduleNativeLineAdvanceTimerIfNeeded"))
        XCTAssertTrue(source.contains("NativeLyricsTimelinePolicy.liveDisplayIndex"))
        XCTAssertTrue(source.contains("waveTimelineEnabled"))
        XCTAssertTrue(source.contains("rowTapHandlers[hoveredRowIndex]"))
        XCTAssertTrue(source.contains("if presentationEngine.isNaturalWaveActive"))
        XCTAssertTrue(source.contains("updateNativeLineMotionSamplingTimer"))
        XCTAssertTrue(source.contains("sampleNativeLineMotionIfNeeded"))
        XCTAssertTrue(source.contains("reportLineMotionFrames(configuration: runtimeConfiguration"))
        XCTAssertFalse(source.contains("fallback: configuration.lineTargetIndices[row.index]"))
        XCTAssertFalse(source.contains("wordFillBucket"))
        XCTAssertFalse(lyricsViewSource.contains("Timer.publish"))
        XCTAssertTrue(lyricsViewSource.contains("lineMotionMonitoringEnabled && !lyricsLayerRendererActive"))
        XCTAssertFalse(lyricsViewSource.contains("scroll.lastVelocity = absVelocity"))
    }
}
